### ISSUE TITLE
Error with react-router when using connectToWpPost

### ISSUE THREAD

**Issue by mr47** [outlandishideas/kasia#22] opened 2016-08-18 19:12 UTC
Hi, 
Tried to use `kasia` for simple helloworld projects
But get this error
<img width="676" alt="2016-08-18 22 04 27" src="https://cloud.githubusercontent.com/assets/651943/17786934/d358dcec-658f-11e6-9ff2-1eaa750d83e6.png">

I get this error when trying switch between pages using `react-router` so
i checked source and maybe something missing or was not rewrote.
its a `connectToWpQuery`
```js
        const { plural, name } = getContentType(contentType)
        const query = props.wordpress.queries[this.queryId]

        if (!query) {
          return {
            kasia: {
              query: { complete: false },
              [name]: null
            }
          }
        }
```
https://github.com/outlandishideas/kasia/blob/master/src/connect/connectWpQuery.js#L132-L133
and this is `connectToWpPost`
```js
        const { queries, entities: _entities } = this.props.wordpress
        const query = queries[this.queryId]

        if (!query) {
          return {
            kasia: {
              query: { complete: false },
              entities: {}
            }
          }
        }
```
https://github.com/outlandishideas/kasia/blob/master/src/connect/connectWpPost.js#L99   

I think they should be same.
PS: also if get free time will submit PR.
Thanks.

**Comment by sdgluck** [comment] 2016-08-19 17:58
Can you share how you are configuring your root reducer? It looks like the `wordpress` object doesn't exist on the store.

The difference in the default `props.kasia` object is intentional. With `connectWpPost` you are receiving a single entity, e.g. `props.kasia.page`, however with `connectWpQuery` you may receive any number of entities, hence the `entities` object.

**Comment by mr47** [comment] 2016-08-20 06:57
@sdgluck i am using a default configuration of https://github.com/davezuko/react-redux-starter-kit

If reload the page its works like a charm but when try to navigate somewhere its triggers this error.
My root reducer is:
```js
export const makeRootReducer = (asyncReducers) => {
  return combineReducers({
    // Add sync reducers here
    router,
    ...asyncReducers
  })
}
```
and then some where:
```js
  const store = createStore(
    makeRootReducer({ ...kasiaReducer }),
    initialState,
    compose(
      applyMiddleware(...middleware),
      ...enhancers
    )
  )
```

**Comment by sdgluck** [comment] 2016-08-20 10:38
Thanks for sharing. Looks like you are configuring the store correctly.

I'm not sure exactly what is causing this issue. If you would like to share the whole project I will find some time to take a better look.

**Comment by mr47** [comment] 2016-08-20 11:14
@sdgluck its a row https://github.com/davezuko/react-redux-starter-kit just added a few lines of code and replaced home view with componet that i already showed nothing special.

**Comment by sdgluck** [comment] 2016-08-20 11:16
Are you configuring `redux-saga`?

**Comment by mr47** [comment] 2016-08-20 11:18
@sdgluck sure as you described in `A slimline example...`

**Comment by sdgluck** [comment] 2016-08-20 11:23
OK great! Well as I said, if you want to share what you've got I'll take a look, as it's not obvious what the problem is.

**Comment by sdgluck** [comment] 2016-08-24 08:48
@mr47 I will close this for now. As I said, if you want to share your project I will take a look at debugging it further.

**Closed by sdgluck** 2016-08-24 08:48 UTC
Labels: question
